package com.webreverse.mcp.mcp.tools

import com.webreverse.mcp.core.common.model.TraceSource
import com.webreverse.mcp.core.common.model.TraceKind
import com.webreverse.mcp.core.common.model.TraceEvent
import com.webreverse.mcp.core.common.model.TraceEventBuffer
import com.webreverse.mcp.core.common.model.TraceCausality
import com.webreverse.mcp.javascript.analysis.ReverseAnalysisEngine
import com.webreverse.mcp.core.common.model.ValueFingerprint
import com.webreverse.mcp.core.common.permission.PermissionScope
import com.webreverse.mcp.core.common.permission.RiskLevel
import com.webreverse.mcp.core.mcp.McpTool
import com.webreverse.mcp.core.mcp.McpToolResult
import com.webreverse.mcp.core.mcp.ToolCategory
import com.webreverse.mcp.workspace.core.AdaptiveInvestigationPlanner
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * 高层 SUPER TOOLS（reverse.* 系列，带 Agent Hints）。
 *
 * 结合 ChatGPT 报告「High-level super tools」结论设计。与底层 400+ 清点工具不同，
 * 超级工具是**编排智能**：一条消息内完成「读取统一追踪事件 → 值指纹关联 → 自适应规划
 * 下一步 → 写入证据库」，并给 Agent 明确的 Hints 指导往下钻取。全部是只读/决策性质，
 * 零副作用（不主动 hook/断点），评级 LOW 风险。
 *
 * 命名空间 reverse.* （HubTools 会聚合为 reverse 枢纽）：
 * 1. `reverse.investigate`：目标 → 自适应调查计划（Planner 状态机 + Agent Hints）
 * 2. `reverse.trace`：统一追踪事件流查询（值指纹 / 异步谱系 / 名称 / 游标增量）
 * 3. `reverse.value_link`：值指纹跨事件/跨图谱关联（回答「这个值从哪来到哪去」）
 * 4. `reverse.introspect`：图谱 + 证据 + 指纹盘点，输出高端结论给 Agent
 */
object ReverseSuperTools {

    /** 规划器实例（无状态，可复用） */
    private val planner = AdaptiveInvestigationPlanner()

    /** 当前调查状态（会话级内存，简单起见全局一份；生产可放入 InvestigationEntity） */
    private val state = java.util.concurrent.ConcurrentHashMap<String, AdaptiveInvestigationPlanner.PlannerState>()

    fun configurePlanner(): AdaptiveInvestigationPlanner = planner

    /**
     * 生成一个自包含、幂等的"明文守护脚本"，交由 user_script.create 注入页面。
     * 目标：对算法入参做不可见采集（btoa/atob/encodeURIComponent/fetch/XHR + 关注端点），
     * 把「输入 → 密文」样本提供给 AI，用于 code.sandbox_eval 离线剥离算法。
     * 全部用非侵入包装（不破坏原行为），只采数、不改结果。
     */
    private fun buildGuardScript(focus: String): String = """
        /* generated by reverse.workflow — 端到端明文守护脚本（幂等，可重复注入） */
        (function(){
          var B = {};
          var send = function(tag, data){ try { if (window.__WRMCP_GS__) window.__WRMCP_GS__(tag, JSON.stringify(data).substring(0,4096)); } catch(e){} };
          B.capture = function(tag, data){ try { if (data) send(tag, data); } catch(e){} };
          try {
            var _btoa = window.btoa;
            window.btoa = function(s){ B.capture('btoa', s); return _btoa.apply(window, arguments); };
          } catch(e){}
          try {
            var _f = window.fetch;
            window.fetch = function(u, o){
              var url = String(u)
              if (url.indexOf('${focus}') !== -1) B.capture('req:'+url, {u:u, o:o || null});
              return _f.apply(window, arguments);
            };
          } catch(e){}
          try {
            var _o = XMLHttpRequest.prototype.open;
            XMLHttpRequest.prototype.open = function(m, u){
              if (String(u).indexOf('${focus}') !== -1) B.capture('xhr:'+String(u), {m: m});
              return _o.apply(this, arguments);
            };
          } catch(e){}
          return 'guard-installed';
        })();
    """.trimIndent()

    fun all(deps: ToolDependencies): List<McpTool> {
        val f = ToolFactory(deps)
        return listOf(
            // ---------------- reverse.analyze_source ----------------
            f.tool(
                "reverse.analyze_source",
                "统一 JS 逆向入口：一次运行 AST/SSA、调用图、污点、Crypto、API Discovery 与热点函数评分，输出 Agent 可直接继续执行的优先级队列。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 30_000,
                capabilities = "reverse,static-analysis,ssa,callgraph,taint,crypto,api-discovery,ranking",
                cost = 5, reliability = 82,
                inputSchema = Schemas.objectSchema(
                    "source" to Schemas.strSchema("JS 源码"),
                    "topN" to Schemas.intSchema("热点函数数量，默认 20"),
                ),
            ) { args ->
                val source = ToolArgs.str(args, "source")
                if (source.isBlank()) return@tool McpToolResult.error("MISSING_SOURCE", "source 必填")
                val topN = ToolArgs.int(args, "topN", 20).coerceIn(1, 100)
                val r = ReverseAnalysisEngine().analyze(source, topN)
                if (!r.ok) return@tool McpToolResult.error("ANALYZE_FAILED", r.error)
                McpToolResult.json(
                    buildJsonObject {
                        put("ok", true)
                        put("sourceChars", r.sourceChars)
                        put("functionCount", r.functionCount)
                        put("endpointCount", r.endpointCount)
                        put("cryptoCount", r.cryptoCount)
                        put("taintFlowCount", r.taintFlowCount)
                        put("parserRiskSignals", JsonArray(r.parserRiskSignals.map(::JsonPrimitive)))
                        put("intelligence", buildJsonObject {
                            put("readiness", r.intelligence.readiness)
                            put("stringsRecovered", r.intelligence.stringsRecovered)
                            put("endpointsRecovered", r.intelligence.endpointsRecovered)
                            put("tokenSignals", r.intelligence.tokenSignals)
                            put("cryptoSignals", r.intelligence.cryptoSignals)
                            put("wasmSignals", r.intelligence.wasmSignals)
                            put("jsvmpSignals", r.intelligence.jsvmpSignals)
                            put("antiDebugSignals", r.intelligence.antiDebugSignals)
                            put("bundlerSignals", r.intelligence.bundlerSignals)
                            put("pipelineHints", JsonArray(r.intelligence.pipelineHints.take(40).map(::JsonPrimitive)))
                            put("warnings", JsonArray(r.intelligence.warnings.map(::JsonPrimitive)))
                            put("targets", JsonArray(r.intelligence.targets.take(30).map { t ->
                                buildJsonObject {
                                    put("kind", t.kind.name); put("name", t.name); put("line", t.line)
                                    put("score", t.score); put("confidence", t.confidence)
                                    put("evidence", JsonArray(t.evidence.take(6).map { e ->
                                        buildJsonObject { put("kind", e.kind); put("line", e.line); put("confidence", e.confidence); put("detail", e.detail) }
                                    }))
                                    put("nextActions", JsonArray(t.nextActions.map(::JsonPrimitive)))
                                }
                            }))
                        })
                        put("hotFunctions", JsonArray(r.hotFunctions.map { fn ->
                            buildJsonObject {
                                put("id", fn.id); put("name", fn.name); put("line", fn.line)
                                put("score", fn.score); put("callers", fn.callers); put("callees", fn.callees); put("taintedFlows", fn.taintedFlows)
                                put("reasons", JsonArray(fn.reasons.map(::JsonPrimitive)))
                            }
                        }))
                        put("findings", JsonArray(r.findings.map { fnd ->
                            buildJsonObject {
                                put("type", fnd.type.name); put("name", fnd.name); put("line", fnd.line); put("confidence", fnd.confidence)
                                put("reasons", JsonArray(fnd.reasons.map(::JsonPrimitive)))
                                put("nextActions", JsonArray(fnd.nextActions.map(::JsonPrimitive)))
                            }
                        }))
                        put("next", r.hotFunctions.firstOrNull()?.let { "优先追踪 ${it.name}，再用 reverse.trace / reverse.value_link / reverse.validate 闭环" }
                            ?: r.intelligence.targets.firstOrNull()?.let { "优先追踪 ${it.kind.name}:${it.name}，再做 runtime capture + reverse.validate" }
                            ?: "优先进行 network.recon")
                    },
                )
            },

            // ---------------- reverse.intelligence（ raw-source intelligence） ----------------
            f.tool(
                "reverse.intelligence",
                "增强型原始源码情报层：即使 AST/SSA 解析不完整，也恢复常量字符串、拼接 URL、token/auth、Crypto/编码/随机数、WASM、JSVMP、anti-debug 与 bundler 信号，并输出证据加权的下一步目标。用于复杂混淆、动态代码、超大 chunk 的第一轮侦察。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 20_000,
                capabilities = "reverse,raw-source,intelligence,endpoint,token,crypto,wasm,jsvmp,anti-debug,bundler",
                cost = 3, reliability = 90,
                inputSchema = Schemas.objectSchema(
                    "source" to Schemas.strSchema("JS 源码"),
                    "topN" to Schemas.intSchema("返回的高价值目标数，默认 60"),
                ),
            ) { args ->
                val source = ToolArgs.str(args, "source")
                if (source.isBlank()) return@tool McpToolResult.error("MISSING_SOURCE", "source 必填")
                val topN = ToolArgs.int(args, "topN", 60).coerceIn(1, 200)
                val r = com.webreverse.mcp.javascript.analysis.ReverseIntelligenceEngine().analyze(source, topN)
                McpToolResult.json(
                    buildJsonObject {
                        put("ok", r.ok)
                        put("sourceChars", r.sourceChars)
                        put("sourceLines", r.sourceLines)
                        put("stringsRecovered", r.stringsRecovered)
                        put("endpointsRecovered", r.endpointsRecovered)
                        put("tokenSignals", r.tokenSignals)
                        put("cryptoSignals", r.cryptoSignals)
                        put("wasmSignals", r.wasmSignals)
                        put("jsvmpSignals", r.jsvmpSignals)
                        put("antiDebugSignals", r.antiDebugSignals)
                        put("bundlerSignals", r.bundlerSignals)
                        put("readiness", r.readiness)
                        put("degradedParserRecovery", r.degradedParserRecovery)
                        put("pipelineHints", JsonArray(r.pipelineHints.map(::JsonPrimitive)))
                        put("warnings", JsonArray(r.warnings.map(::JsonPrimitive)))
                        put("strings", JsonArray(r.strings.take(200).map { sf ->
                            buildJsonObject {
                                put("value", sf.value.take(4096))
                                put("line", sf.line)
                                put("expression", sf.expression.take(1000))
                                put("decoded", sf.decoded)
                            }
                        }))
                        put("targets", JsonArray(r.targets.map { t ->
                            buildJsonObject {
                                put("kind", t.kind.name)
                                put("name", t.name)
                                put("line", t.line)
                                put("score", t.score)
                                put("confidence", t.confidence)
                                put("evidence", JsonArray(t.evidence.map { e ->
                                    buildJsonObject {
                                        put("kind", e.kind); put("line", e.line); put("confidence", e.confidence)
                                        put("detail", e.detail); put("snippet", e.snippet)
                                    }
                                }))
                                put("nextActions", JsonArray(t.nextActions.map(::JsonPrimitive)))
                            }
                        }))
                    }
                )
            },

            // ---------------- reverse.workflow（ 端到端自动逆向闭环） ----------------
            f.tool(
                "reverse.workflow",
                "一键逆向流水线编排：源 → VMP 验证 → 热点/加密画像 → 离线公式剥离建议 → 生成可复用守护脚本（capture 明文），把「发现→假设→验证→产出」收敛为一条可执行闭环",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                inputSchema = Schemas.objectSchema(
                    "source" to Schemas.strSchema("JS 源码（离线，可直接使用 file.read 拿到的内容）"),
                    "endpointContains" to Schemas.strSchema("关注端点关键词（如 sign/wdf），用于聚焦"),
                ),
            ) { args ->
                val source = ToolArgs.str(args, "source")
                if (source.isBlank()) return@tool McpToolResult.error("MISSING_SOURCE", "source 必填")
                val focus = ToolArgs.str(args, "endpointContains").ifBlank { "sign" }
                val r = ReverseAnalysisEngine().analyze(source, 20)
                val verdict = runCatching { com.webreverse.mcp.javascript.analysis.VmpDetector().verify(source) }.getOrNull()
                val hot = r.hotFunctions.filter { it.name.contains(focus, ignoreCase = true) || it.reasons.any { x -> x.contains(focus, ignoreCase = true) } }
                val steps = listOf(
                    "1. 若页面在线：network.recon/network.list 抓 ${focus} 请求，记录 query/header/body",
                    "2. 静态定位：reverse.analyze_source 已定位密钥相关函数；JSVMP 时用 vmp.verify 校准家族后走 jsvmp.analyze/ir_translate",
                    "3. 明文捕获：粘贴下方 guardScript → user_script.create，页面重放时 console/output 捕获未加密入参",
                    "4. 公式剥离：对捕获的密文/入参用 code.sandbox_eval 离线试 base64→hex→异或/位移链",
                    "5. 验证闭环：reverse.validate 复现签名值，比对服务器接收值判真",
                )
                val guardScript = buildGuardScript(focus)
                McpToolResult.json(
                    buildJsonObject {
                        put("ok", true)
                        put("focus", focus)
                        put("vmpVerdict", verdict?.let {
                            buildJsonObject {
                                put("family", it.family); put("confidence", it.confidence); put("reliability", it.reliability)
                                put("contradicting", JsonArray(it.contradicting.map(::JsonPrimitive)))
                            }
                        } ?: buildJsonObject {})
                        put("hotFocusFunctions", JsonArray(hot.take(8).map { fn ->
                            buildJsonObject { put("name", fn.name); put("line", fn.line); put("score", fn.score) }
                        }))
                        put("cryptoCount", r.cryptoCount)
                        put("plan", JsonArray(steps.map(::JsonPrimitive)))
                        put("guardScript", guardScript)
                        put(
                            "hint",
                            JsonPrimitive(
                                (verdict?.reliability ?: "n/a") + "；将 guardScript 存为用户脚本后重放页面捕获入参，再配合 code.sandbox_eval 离线剥离算法",
                            ),
                        )
                    },
                )
            },

            // ---------------- reverse.causality ----------------
            f.tool(
                "reverse.causality",
                "统一 Trace 因果链：使用 parentEventId、值指纹、异步链、执行上下文和近邻 callsite 生成有证据等级的因果路径，减少纯时间窗误判。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                capabilities = "trace,causality,fingerprint,async-lineage",
                cost = 2, reliability = 88,
                inputSchema = Schemas.objectSchema(
                    "targetSeq" to Schemas.longSchema("目标事件 seq；缺省时取最近事件"),
                    "maxDepth" to Schemas.intSchema("最大回溯深度，默认 24"),
                ),
            ) { args ->
                val buf = deps.evidenceStore.traceBuffer
                val events = buf.all()
                if (events.isEmpty()) return@tool McpToolResult.error("NO_TRACE", "当前没有统一追踪事件")
                val requestedTarget = ToolArgs.long(args, "targetSeq", Long.MIN_VALUE)
                val target = if (requestedTarget == Long.MIN_VALUE) {
                    events.maxByOrNull { e -> e.seq }?.seq
                        ?: return@tool McpToolResult.error("NO_TRACE", "当前没有事件")
                } else requestedTarget
                val paths = TraceCausality.findPaths(events, target, ToolArgs.int(args, "maxDepth", 24).coerceIn(2, 64))
                McpToolResult.json(buildJsonObject {
                    put("targetSeq", target)
                    put("pathCount", paths.size)
                    put("paths", JsonArray(paths.map { path ->
                        buildJsonObject {
                            put("rootSeq", path.rootSeq); put("leafSeq", path.leafSeq); put("confidence", path.confidence)
                            put("explanation", path.explanation)
                            put("events", JsonArray(path.events.map { e -> buildJsonObject { put("seq", e.seq); put("kind", e.kind.name); put("source", e.source.name); put("name", e.name); put("line", e.line) } }))
                            put("edges", JsonArray(path.edges.map { e -> buildJsonObject { put("from", e.fromSeq); put("to", e.toSeq); put("relation", e.relation.name); put("score", e.score); put("evidence", JsonArray(e.evidence.map(::JsonPrimitive))) } }))
                        }
                    }))
                    put("hint", "优先采用 VALUE_FLOW / PARENT 高分边；ASYNC_CONTINUATION 和 CALLSITE 作为辅助证据")
                })
            },

            // ---------------- reverse.investigate ----------------
            f.tool(
                "reverse.investigate",
                "目标驱动自适应调查计划：根据目标返回最优下一步行动 + 期望信号 + Agent Hints（超级工具，取代手动编排）",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                capabilities = "planning,heuristic",
                cost = 1, reliability = 65,
                inputSchema = Schemas.objectSchema(
                    "goal" to Schemas.enumSchema("调查目标", "SIGNATURE", "TOKEN_TRACE", "REVERSE_API", "CRYPTO_LOCATE", "GENERAL"),
                    "confirmedSignals" to Schemas.strSchema("已确认信号，逗号分隔（recon_done/crypto_found/endpoint_chain/...）"),
                    "sessionId" to Schemas.strSchema("会话 id（缺省取当前上下文）"),
                    "topN" to Schemas.intSchema("返回 Top N 个行动，默认 3"),
                ),
            ) { args ->
                val goal = runCatching {
                    AdaptiveInvestigationPlanner.Goal.valueOf(ToolArgs.str(args, "goal").ifBlank { "GENERAL" })
                }.getOrElse { AdaptiveInvestigationPlanner.Goal.GENERAL }
                val confirmed = ToolArgs.str(args, "confirmedSignals")
                    .split(',')
                    .map { it.trim() }
                    .filter { it.isNotEmpty() }
                    .toSet()
                val sid = ToolArgs.str(args, "sessionId").ifBlank {
                    deps.context()?.sessionId ?: "default"
                }
                val topN = ToolArgs.int(args, "topN", 3)

                // 同一 session 切换调查目标时不能复用旧目标的 keySignals/confidence。
                // 否则 SIGNATURE → TOKEN_TRACE 会继承错误的完成度。
                val cur = state[sid]?.takeIf { it.goal == goal }
                    ?: AdaptiveInvestigationPlanner.PlannerState(goal = goal)
                val advanced = planner.advance(cur, confirmed)
                state[sid] = advanced
                val plan = planner.planNext(advanced, topN)

                McpToolResult.json(
                    buildJsonObject {
                        put("goal", goal.name)
                        put("confidence", (advanced.confidence * 100).toInt())
                        put("confirmedSignals", JsonArray(advanced.confirmedSignals.map { JsonPrimitive(it) }))
                        put(
                            "actions",
                            JsonArray(
                                plan.map {
                                    buildJsonObject {
                                        put("precedence", it.precedence)
                                        put("type", it.type.name)
                                        put("action", it.action)
                                        put("tool", it.toolHint)
                                        put("expectation", it.expectation)
                                        put("reason", it.reason)
                                        put("weight", (it.weight * 100).toInt())
                                    }
                                },
                            ),
                        )
                        put(
                            "hint",
                            JsonPrimitive(
                                plan.firstOrNull()?.let {
                                    "优先执行 ${it.toolHint}（${it.action}），关注 ${it.expectation}"
                                } ?: "所有行动目标信号已覆盖，进入验证闭环或结束调查",
                            ),
                        )
                    },
                )
            },

            // ---------------- reverse.trace ----------------
            f.tool(
                "reverse.trace",
                "统一追踪事件流查询：按名称/指纹/异步链/游标增量取回（DynamicTracer/Hook/WASM 的统一 TraceEvent 回放）",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                inputSchema = Schemas.objectSchema(
                    "mode" to Schemas.enumSchema("查询模式", "recent", "by_name", "by_fingerprint", "chain", "value_path", "stats"),
                    "name" to Schemas.strSchema("[by_name/chain] 函数名/URL/链 id"),
                    "fingerprint" to Schemas.strSchema("[by_fingerprint] 值指纹"),
                    "sinceSeq" to Schemas.longSchema("[recent] 游标：只取 seq > 此值（增量续传）"),
                    "limit" to Schemas.intSchema("返回条数上限"),
                ),
            ) { args ->
                val buf = deps.evidenceStore.traceBuffer
                val mode = ToolArgs.str(args, "mode").ifBlank { "recent" }
                val limit = ToolArgs.int(args, "limit", 100).coerceIn(1, 500)
                McpToolResult.json(
                    buildJsonObject {
                        put("mode", mode)
                        when (mode) {
                            "recent" -> {
                                val since = ToolArgs.long(args, "sinceSeq", -1L)
                                val events = buf.since(since, limit)
                                put("sinceSeq", since)
                                put("lastSeq", buf.lastSeq)
                                put("count", events.size)
                                put("events", JsonArray(events.map { traceEventJson(it) }))
                            }
                            "by_name" -> {
                                val name = ToolArgs.str(args, "name")
                                val events = if (name.isBlank()) buf.all() else buf.findByName(name)
                                put("count", events.size)
                                put("events", JsonArray(events.takeLast(limit).map { traceEventJson(it) }))
                            }
                            "by_fingerprint" -> {
                                val fp = ToolArgs.str(args, "fingerprint")
                                if (fp.isBlank()) return@tool McpToolResult.error("MISSING_FINGERPRINT", "fingerprint 必填")
                                val events = buf.findByFingerprint(fp)
                                put("count", events.size)
                                put("events", JsonArray(events.takeLast(limit).map { traceEventJson(it) }))
                                put("hint", JsonPrimitive("reverse.value_link fingerprint=$fp 查看跨图谱流动"))
                            }
                            "chain" -> {
                                val cid = ToolArgs.str(args, "name")
                                val events = buf.findChain(cid)
                                put("chainId", cid)
                                put("count", events.size)
                                put("events", JsonArray(events.map { traceEventJson(it) }))
                                put("hint", JsonPrimitive("本链事件按 seq 时序展示；异步谱系已回答『谁触发谁』"))
                            }
                            "value_path" -> {
                                val fp = ToolArgs.str(args, "fingerprint")
                                if (fp.isBlank()) return@tool McpToolResult.error("MISSING_FINGERPRINT", "fingerprint 必填")
                                val path = buf.valuePropagation(fp)
                                put("fingerprint", fp)
                                put("span", deps.evidenceStore.fingerprintSpan(fp)?.let {
                                    buildJsonObject {
                                        put("firstSeen", it.first); put("lastSeen", it.second)
                                    }
                                } ?: buildJsonObject {})
                                put("path", JsonArray(path.map { traceEventJson(it) }))
                            }
                            "stats" -> put("stats", bufferStatsJson(buf))
                            else -> return@tool McpToolResult.error("BAD_MODE", "未知模式: $mode")
                        }
                    },
                )
            },

            // ---------------- reverse.value_link ----------------
            f.tool(
                "reverse.value_link",
                "值指纹关联：同一指纹流经的所有 TraceEvent 与图谱节点，回答『某关键值从哪来到哪去』（统一数据流核心）",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                inputSchema = Schemas.objectSchema(
                    "value" to Schemas.strSchema("原始值（自动算指纹）或直接传 fingerprint"),
                    "fingerprint" to Schemas.strSchema("值指纹（提供则跳过 value 计算）"),
                    "topN" to Schemas.intSchema("返回 Top 关联，默认 10"),
                ),
            ) { args ->
                var fp = ToolArgs.str(args, "fingerprint")
                if (fp.isBlank()) {
                    val value = ToolArgs.str(args, "value")
                    if (value.isBlank()) return@tool McpToolResult.error("MISSING_VALUE", "value 或 fingerprint 必填")
                    fp = ValueFingerprint.of(value) ?: return@tool McpToolResult.error("SHORT_VALUE", "值过短/过长无法指纹（3~4096 字符）")
                }
                val buf = deps.evidenceStore.traceBuffer
                val events = buf.findByFingerprint(fp)
                val nodes = deps.evidenceStore.nodesByFingerprint(fp)
                val evidences = deps.evidenceStore.evidenceByFingerprint(fp)
                McpToolResult.json(
                    buildJsonObject {
                        put("fingerprint", fp)
                        put("events", JsonArray(events.takeLast(50).map { traceEventJson(it) }))
                        put("eventCount", events.size)
                        put("graphNodes", JsonArray(nodes.map {
                            buildJsonObject {
                                put("key", it.key); put("label", it.label); put("type", it.type.name)
                            }
                        }))
                        put("evidenceCount", evidences.size)
                        put("evidenceTitles", JsonArray(evidences.takeLast(20).map { JsonPrimitive(it.title) }))
                        put(
                            "hint",
                            JsonPrimitive(
                                buildString {
                                    append("该值流经 ")
                                    append(events.size).append(" 个事件 / ")
                                    append(nodes.size).append(" 个图谱节点")
                                    if (nodes.isNotEmpty()) {
                                        append("；图谱链路：graph.query key=")
                                        append(nodes.first().key)
                                        append(" 展开邻接")
                                    }
                                },
                            ),
                        )
                    },
                )
            },

            // ---------------- reverse.signature_candidates ----------------
            f.tool(
                "reverse.signature_candidates",
                "从真实 Trace 自动发现请求↔签名候选：以值指纹为硬证据，叠加上下文、异步链、父事件和 crypto 命名证据，保留 Top-K 假设供验证。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                capabilities = "reverse,trace,signature,causality,fingerprint,network",
                cost = 3, reliability = 96,
                inputSchema = Schemas.objectSchema(
                    "endpointContains" to Schemas.strSchema("可选 URL/路径过滤"),
                    "topK" to Schemas.intSchema("每请求保留候选数，默认 5"),
                ),
            ) { args ->
                val report = com.webreverse.mcp.core.common.model.TraceSignatureCorrelator.analyze(
                    deps.evidenceStore.traceBuffer.all(),
                    ToolArgs.str(args, "endpointContains"),
                    ToolArgs.int(args, "topK", 5),
                )
                McpToolResult.json(buildJsonObject {
                    put("requests", report.requests)
                    put("requestCoverage", report.requestCoverage)
                    put("strongCoverage", report.strongCoverage)
                    put("candidates", JsonArray(report.candidates.take(200).map { c ->
                        buildJsonObject {
                            put("requestSeq", c.requestSeq); put("signerSeq", c.signerSeq)
                            put("request", c.requestName); put("signer", c.signerName)
                            put("score", c.score); put("gapMs", c.gapMs)
                            put("fingerprints", JsonArray(c.matchedFingerprints.map(::JsonPrimitive)))
                            put("evidence", JsonArray(c.evidence.map(::JsonPrimitive)))
                        }
                    }))
                    put("hint", JsonPrimitive("对 score>=0.82 的候选继续 reverse.causality，再进入实际多样本 validation；不要只凭时间顺序确认签名。"))
                })
            },

            // ---------------- reverse.introspect ----------------
            f.tool(
                "reverse.introspect",
                "逆向现场盘点：图谱/证据/值指纹/事件流统计，输出逆向最有价值的枢纽与关键中间值（超级工具）",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                inputSchema = Schemas.objectSchema(
                    "topN" to Schemas.intSchema("Top 数量，默认 15"),
                ),
            ) { args ->
                val store = deps.evidenceStore
                val topN = ToolArgs.int(args, "topN", 15).coerceIn(5, 100)
                val stats = store.stats()
                val hubs = store.topNodes(topN)
                val edges = store.topEdges(topN)
                val fps = store.topFingerprints(topN)
                val bufStats = bufferStatsJson(store.traceBuffer)
                McpToolResult.json(
                    buildJsonObject {
                        put("graph", buildJsonObject {
                            put("nodeCount", stats["nodeCount"] as? Int ?: 0)
                            put("edgeCount", stats["edgeCount"] as? Int ?: 0)
                            put("evidenceCount", stats["evidenceCount"] as? Int ?: 0)
                        })
                        put("hubNodes", JsonArray(hubs.map {
                            buildJsonObject {
                                put("key", it.key); put("label", it.label); put("type", it.type.name); put("weight", it.weight)
                            }
                        }))
                        put("topEdges", JsonArray(edges.map {
                            buildJsonObject {
                                put("from", it.from); put("to", it.to); put("type", it.type.name); put("weight", it.weight)
                            }
                        }))
                        put("hotValues", JsonArray(fps.map {
                            buildJsonObject {
                                put("fingerprint", it.first); put("occurrences", it.second)
                            }
                        }))
                        put("trace", bufStats)
                        put(
                            "hint",
                            JsonPrimitive(
                                buildString {
                                    append("逆向入口建议：")
                                    val crypto = hubs.firstOrNull { it.type.name == "CRYPTO" }
                                    val endpoint = hubs.firstOrNull { it.type.name == "ENDPOINT" }
                                    when {
                                        crypto != null -> append("关注加密枢纽 crypto：${crypto.key}")
                                        endpoint != null -> append("关注接口枢纽 endpoint：${endpoint.key}")
                                        else -> append("hubs 为空，先跑 pipeline.run name=recon 侦察")
                                    }
                                },
                            ),
                        )
                    },
                )
            },

            // ---------------- reverse.deep_analyze ----------------
            f.tool(
                "reverse.deep_analyze",
                "深度逆向统一入口：对象/属性 Memory-Flow、跨函数参数/返回值、异步边界、网络 Sink、Crypto/WASM 绑定与质量门一次分析。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 45_000,
                capabilities = "reverse,deep-analysis,object-memory,interprocedural,async,network,crypto,wasm,quality-gate",
                cost = 8, reliability = 94,
                inputSchema = Schemas.objectSchema(
                    "source" to Schemas.strSchema("JS 源码"),
                ),
            ) { args ->
                val source = ToolArgs.str(args, "source")
                if (source.isBlank()) return@tool McpToolResult.error("MISSING_SOURCE", "source 必填")
                val deep = com.webreverse.mcp.javascript.analysis.DeepReverseAnalyzer().analyze(source)
                val base = ReverseAnalysisEngine().analyze(source, 20)
                val q = com.webreverse.mcp.javascript.analysis.ReverseQualityGate().evaluate(
                    deep = deep,
                    validationConfidence = 0.0,
                    traceCoverage = 0.0,
                    parserRiskSignals = base.parserRiskSignals,
                )
                McpToolResult.json(buildJsonObject {
                    put("ok", deep.ok)
                    if (!deep.ok) put("error", deep.error)
                    put("metrics", buildJsonObject {
                        put("objectMemoryCoverage", deep.metrics.objectMemoryCoverage)
                        put("interproceduralCoverage", deep.metrics.interproceduralCoverage)
                        put("asyncCoverage", deep.metrics.asyncCoverage)
                        put("networkBindingCoverage", deep.metrics.networkBindingCoverage)
                        put("cryptoBindingCoverage", deep.metrics.cryptoBindingCoverage)
                        put("wasmBoundaryCoverage", deep.metrics.wasmBoundaryCoverage)
                        put("explainability", deep.metrics.explainability)
                        put("overallReadiness", deep.metrics.overallReadiness)
                    })
                    put("propertyFacts", JsonArray(deep.propertyFacts.take(200).map { x ->
                        buildJsonObject { put("path", x.path); put("operation", x.operation); put("line", x.line); put("function", x.function); put("expression", x.expression) }
                    }))
                    put("asyncFacts", JsonArray(deep.asyncFacts.take(100).map { x ->
                        buildJsonObject { put("api", x.api); put("callback", x.callbackHint); put("line", x.line); put("function", x.function); put("confidence", x.confidence) }
                    }))
                    put("networkSinks", JsonArray(deep.networkSinks.take(100).map { x -> buildJsonObject { put("id", x.id); put("label", x.label); put("line", x.line); put("confidence", x.confidence) } }))
                    put("cryptoBindings", JsonArray(deep.cryptoBindings.take(100).map { x -> buildJsonObject { put("id", x.id); put("label", x.label); put("line", x.line); put("confidence", x.confidence) } }))
                    put("wasmHints", JsonArray(deep.wasmHints.take(100).map { x -> buildJsonObject { put("id", x.id); put("label", x.label); put("line", x.line); put("confidence", x.confidence) } }))
                    put("qualityGate", buildJsonObject {
                        put("verdict", q.verdict.name); put("score", q.score)
                        put("blockers", JsonArray(q.blockers.map(::JsonPrimitive)))
                        put("nextActions", JsonArray(q.nextActions.map(::JsonPrimitive)))
                    })
                    put("hint", JsonPrimitive("优先使用高 confidence 的 network/crypto/WASM sink；然后进入 value fingerprint + causality + validation。"))
                })
            },

            // ---------------- reverse.quality_gate ----------------
            f.tool(
                "reverse.quality_gate",
                "逆向质量门：把深度分析、Trace 覆盖率、真实验证置信度综合成 INVESTIGATE/VALIDATE/CONFIRMED。",
                ToolCategory.REVERSE,
                PermissionScope.READ_PAGE, RiskLevel.LOW,
                timeoutMs = 10_000,
                capabilities = "reverse,quality,confidence,validation",
                cost = 2, reliability = 96,
                inputSchema = Schemas.objectSchema(
                    "source" to Schemas.strSchema("JS 源码"),
                    "validationConfidence" to Schemas.doubleSchema("真实样本验证置信度 0..1"),
                    "traceCoverage" to Schemas.doubleSchema("运行时 trace 覆盖率 0..1"),
                ),
            ) { args ->
                val source = ToolArgs.str(args, "source")
                if (source.isBlank()) return@tool McpToolResult.error("MISSING_SOURCE", "source 必填")
                val base = ReverseAnalysisEngine().analyze(source, 20)
                val deep = com.webreverse.mcp.javascript.analysis.DeepReverseAnalyzer().analyze(source)
                val requestedValidation = ToolArgs.double(args, "validationConfidence", -1.0)
                val requestedTrace = ToolArgs.double(args, "traceCoverage", -1.0)
                val traceReport = com.webreverse.mcp.core.common.model.TraceSignatureCorrelator.analyze(deps.evidenceStore.traceBuffer.all())
                val validation = if (requestedValidation >= 0.0) requestedValidation.coerceIn(0.0, 1.0) else 0.0
                val trace = if (requestedTrace >= 0.0) requestedTrace.coerceIn(0.0, 1.0) else traceReport.strongCoverage.coerceIn(0.0, 1.0)
                val q = com.webreverse.mcp.javascript.analysis.ReverseQualityGate().evaluate(
                    deep, validation, trace, base.parserRiskSignals,
                )
                McpToolResult.json(buildJsonObject {
                    put("verdict", q.verdict.name); put("score", q.score)
                    put("derivedTraceCoverage", trace)
                    put("derivedValidationConfidence", validation)
                    put("dimensions", JsonArray(q.dimensions.map { d ->
                        buildJsonObject {
                            put("name", d.name); put("score", d.score)
                            put("evidence", JsonArray(d.evidence.map(::JsonPrimitive)))
                            put("gaps", JsonArray(d.gaps.map(::JsonPrimitive)))
                        }
                    }))
                    put("blockers", JsonArray(q.blockers.map(::JsonPrimitive)))
                    put("nextActions", JsonArray(q.nextActions.map(::JsonPrimitive)))
                })
            },
        )
    }

    // ---------------- 序列化辅助 ----------------

    private fun traceEventJson(e: TraceEvent) = buildJsonObject {
        put("seq", e.seq)
        put("ts", e.ts)
        put("source", e.source.name)
        put("kind", e.kind.name)
        put("name", e.name)
        if (e.asyncChainId.isNotBlank()) put("chainId", e.asyncChainId)
        if (e.parentEventId >= 0) put("parentSeq", e.parentEventId)
        if (e.output != null) put("output", e.output!!.raw)
        if (e.input != null) put("input", e.input!!.raw)
        if (e.error.isNotBlank()) put("error", e.error)
        val fps = e.values.mapNotNull { if (it.hasFingerprint) it.fingerprint else null }
        if (fps.isNotEmpty()) put("fingerprints", JsonArray(fps.map { JsonPrimitive(it) }))
    }

    private fun bufferStatsJson(buf: TraceEventBuffer) = buildJsonObject {
        put("size", buf.stats().size)
        put("lastSeq", buf.stats().lastSeq)
        put("distinctFingerprints", buf.stats().distinctFingerprints)
        put("distinctChains", buf.stats().distinctChains)
        put("bySource", buildJsonObject { buf.stats().bySource.forEach { (k, v) -> put(k, JsonPrimitive(v)) } })
    }
}