package com.webreverse.mcp.ui.theme

import androidx.compose.ui.graphics.Color

// ==================== Light Color Scheme ====================
val LightPrimary = Color(0xFF00639B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCEE5FF)
val LightOnPrimaryContainer = Color(0xFF001D33)
val LightSecondary = Color(0xFF00696E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF6FF6FC)
val LightOnSecondaryContainer = Color(0xFF002021)
val LightTertiary = Color(0xFF00696E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF6FF6FC)
val LightOnTertiaryContainer = Color(0xFF002021)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF8FDFF)
val LightOnBackground = Color(0xFF001F2A)
val LightSurface = Color(0xFFF8FDFF)
val LightOnSurface = Color(0xFF001F2A)
val LightSurfaceVariant = Color(0xFFDCE3EA)
val LightOnSurfaceVariant = Color(0xFF40484E)
val LightOutline = Color(0xFF70787F)
val LightOutlineVariant = Color(0xFFC0C7CE)
val LightSurfaceContainer = Color(0xFFECF2F8)
val LightSurfaceContainerHigh = Color(0xFFE6ECF2)
val LightSurfaceContainerHighest = Color(0xFFE0E7ED)

// ==================== Dark Color Scheme ====================
val DarkPrimary = Color(0xFF9CCBFF)
val DarkOnPrimary = Color(0xFF003353)
val DarkPrimaryContainer = Color(0xFF004A76)
val DarkOnPrimaryContainer = Color(0xFFCEE5FF)
val DarkSecondary = Color(0xFF4DD9DF)
val DarkOnSecondary = Color(0xFF003738)
val DarkSecondaryContainer = Color(0xFF004F52)
val DarkOnSecondaryContainer = Color(0xFF6FF6FC)
val DarkTertiary = Color(0xFF4DD9DF)
val DarkOnTertiary = Color(0xFF003738)
val DarkTertiaryContainer = Color(0xFF004F52)
val DarkOnTertiaryContainer = Color(0xFF6FF6FC)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0F1418)
val DarkOnBackground = Color(0xFFDEE9F0)
val DarkSurface = Color(0xFF0F1418)
val DarkOnSurface = Color(0xFFDEE9F0)
val DarkSurfaceVariant = Color(0xFF40484E)
val DarkOnSurfaceVariant = Color(0xFFC0C7CE)
val DarkOutline = Color(0xFF8A9299)
val DarkOutlineVariant = Color(0xFF40484E)
val DarkSurfaceContainer = Color(0xFF1B2024)
val DarkSurfaceContainerHigh = Color(0xFF252A2F)
val DarkSurfaceContainerHighest = Color(0xFF303539)

// ==================== DevTools Accent ====================
val DevToolsBlue = Color(0xFF1A73E8)
val DevToolsPurple = Color(0xFF7C4DFF)
val DevToolsTeal = Color(0xFF00BFA5)
val DevToolsOrange = Color(0xFFFF8F00)
val DevToolsRed = Color(0xFFE53935)
val DevToolsGreen = Color(0xFF43A047)
val DevToolsPink = Color(0xFFD81B60)
val DevToolsCyan = Color(0xFF00ACC1)
